/* 自动生成，请勿手改 —— 改 strings.zh.txt 后跑 scripts/live/gen-strings.py */
#ifndef GK3_STRINGS_H
#define GK3_STRINGS_H

#define S_WELCOME_TITLE           "让我们在这台电脑上安装 Android"
#define S_WELCOME_SUB             "HUAWEI MateBook E Go · Snapdragon 8cx Gen 3 (sc8280xp)"
#define S_WELCOME_BODY            "我们将把 Android 安装到你的内置固态硬盘上。\n在接下来的步骤中，你可以选择清除整个磁盘，或者保留现有系统，仅使用可用空间。"
#define S_WELCOME_NOTE            "你的设备使用 UEFI 引导，而不是 fastboot。安装完成后，systemd-boot 将为你启动系统，\n内核和 ramdisk 会以普通文件的形式放置在 EFI 分区上。"
#define S_BTN_START               "开始使用"
#define S_BTN_QUIT                "退出到终端"
#define S_BTN_BACK                "返回"
#define S_BTN_NEXT                "下一步"
#define S_BTN_REBOOT              "立即重新启动"
#define S_DISK_TITLE              "你想将 Android 安装在哪里？"
#define S_DISK_SUB                "选择一个磁盘以继续。可移动介质（例如你正在使用的安装 U 盘）不会显示在这里。"
#define S_DISK_NONE               "我们找不到可以安装的磁盘。请检查你的内置硬盘是否已被识别（可以在终端中运行 lsblk）。"
#define S_MODE_TITLE              "你希望如何安装？"
#define S_MODE_SUB                "此选择将决定磁盘上现有内容的去留。请在继续之前仔细确认。"
#define S_MODE_WIPE_TITLE         "清除整个磁盘"
#define S_MODE_WIPE_WARN          "此磁盘上的所有内容都将被删除，包括其他操作系统。"
#define S_MODE_WIPE_BODY          "这将为你提供最干净的分区布局，Android 将获得全部空间。\n如果这台电脑只用来运行 Android，我们建议选择此项。"
#define S_MODE_ALONG_TITLE        "保留现有系统"
#define S_MODE_ALONG_OK           "我们只会使用可用空间，不会对你现有的分区进行任何更改。"
#define S_MODE_ALONG_INFO         "可用空间：%s\n我们将重用你现有的 EFI 分区：%s"
#define S_MODE_WHY_NOESP          "此磁盘上没有 EFI 系统分区 —— 这意味着它上面没有可以保留的 UEFI 系统"
#define S_MODE_WHY_NOROOM         "可用空间不足 20.2 GiB。请先返回现有系统压缩分区以腾出一些空间（在 Windows 中，可以使用“磁盘管理”来完成此操作）"
#define S_OPTS_TITLE              "快速设置"
#define S_OPTS_SUB                "我们已经为你选择了推荐的设置。如果不确定，直接点击“下一步”即可。"
#define S_OPTS_RESCUE_TITLE       "同时安装救援系统"
#define S_OPTS_RESCUE_BODY        "这将占用 1 GiB 空间，其中包含一套在内存中运行的 Linux（带有 ssh 和分区工具）。\n当 Android 无法启动时，它是远程访问这台设备的唯一方式。我们强烈建议保留此项。"
#define S_OPTS_DATA               "/data 将获得所有剩余空间：大约 %s"
#define S_OPTS_LATER              "（我们将在下一步为你计算）"
#define S_CONFIRM_TITLE           "在开始之前，请确认一下"
#define S_CONFIRM_SUB             "这是最后一步。在此之后，我们将开始对磁盘进行更改。"
#define S_CONFIRM_WIPE_HEAD       "以下分区将【全部被删除】："
#define S_CONFIRM_NOPARTS         "（此磁盘上目前没有任何分区）"
#define S_CONFIRM_MORE            "…以及其余分区"
#define S_CONFIRM_ALONG_HEAD      "你现有的分区【不会受到任何影响】。我们只会使用可用空间。"
#define S_CONFIRM_ALONG_BODY      "我们将创建 %s 的 Android 分区，并在你的 EFI 分区 %s 中添加两个启动项。"
#define S_CONFIRM_RESCUE          "救援系统：%s"
#define S_WORD_INSTALL            "安装"
#define S_WORD_NOINSTALL          "不安装"
#define S_CONFIRM_HOLD_IDLE       "按住 2 秒以开始安装"
#define S_CONFIRM_HOLD_BUSY       "请继续按住…… %d%%"
#define S_RUN_TITLE               "我们正在为你安装 Android"
#define S_RUN_SUB                 "这可能需要几分钟时间。请不要关闭电源。"
#define S_DONE_TITLE              "一切就绪！"
#define S_DONE_BODY               "请移除安装介质。重新启动后，你将进入 Android。%s"
#define S_DONE_RESCUE             "\n\n我们还为你安装了救援系统：你可以在开机菜单中选择它。当 Android 无法启动时，它是远程访问这台设备的唯一方式。"
#define S_FAIL_TITLE              "哎呀，出错了"
#define S_FAIL_SUB                "你的磁盘可能处于未完成的中间状态。请不要立即重启回原系统 —— 我们建议先保存或拍下下方的日志。"
#define S_ERR_NOSPACE             "空间不足：当前可用 %ld MiB，但我们至少需要 %ld MiB"
#define S_ERR_PLAN                "我们无法计算分区方案：%s"
#define S_ERR_NOFREE              "此磁盘上没有可用空间"
#define S_ERR_BACKEND             "我们无法启动安装后端"
#define S_ERR_EXIT                "安装未能完成（退出码 %d）"
#define S_STEP_PREP               "正在准备一些事情……"
#define S_STEP_DONE               "即将完成……"

#endif
